import { Request, Response } from 'express';
import { githubService } from '../services/githubService';
import { query } from '../config/db';
import { EventBus } from '../services/eventBus';

export async function createAiFixPr(req: Request, res: Response): Promise<void> {
  const { runId, repoUrl, filePath, fixDescription, proposedCode } = req.body;

  try {
    const targetRepo = repoUrl || 'https://github.com/deploymate-org/deploymate-app';
    const targetFile = filePath || 'src/services/telemetry.ts';
    const branchName = `fix/ai-autofix-${Date.now().toString(36)}`;
    
    const patchCode = proposedCode || `// AI Automated Patch generated by DEPLOYMATE Gemini AIOps Engine\n// Issue fix description: ${fixDescription || 'Resolved memory pool exhaust and runtime crash'}\n\nexport const sanitizeConfig = (cfg: any) => {\n  if (!cfg) return {};\n  return { ...cfg, timeoutMs: 5000, retryAttempts: 3 };\n};\n`;

    const prTitle = `[AIOps Auto-Fix] ${fixDescription || 'Automated Pipeline & Runtime Failure Remediation'}`;
    const prBody = `### 🤖 DEPLOYMATE Gemini AIOps Automated Patch\n\n` +
      `**Triggered by Pipeline Run:** \`${runId || 'PR-RUN-' + Math.floor(Math.random() * 1000)}\`\n\n` +
      `#### Root Cause & Remediation Summary:\n` +
      `${fixDescription || 'Identified connection exhaustion and missing error boundaries. Added sanitization and safe default fallbacks.'}\n\n` +
      `#### Target File:\n` +
      `\`${targetFile}\`\n\n` +
      `*Generated automatically by DEPLOYMATE Cloud Operations Platform.*`;

    const result = await githubService.createFixPullRequest({
      repoUrl: targetRepo,
      branchName,
      filePath: targetFile,
      fileContent: patchCode,
      prTitle,
      prBody
    });

    // Record Audit Log entry
    await query(
      `INSERT INTO audit_logs (action, resource, details)
       VALUES ($1, $2, $3)`,
      [
        'AI_FIX_PR_CREATED',
        `GitHubPR#${result.prNumber}`,
        JSON.stringify({ prUrl: result.prUrl, branch: branchName, runId, isSimulated: result.isSimulated })
      ]
    );

    // Emit EventBus event
    await EventBus.emit({
      eventType: 'AI_PULL_REQUEST_CREATED',
      source: 'ai',
      severity: 'INFO',
      resource: `GitHubPR#${result.prNumber}`,
      metadata: { prUrl: result.prUrl, branch: branchName, runId }
    });

    res.status(200).json({
      status: 'SUCCESS',
      prUrl: result.prUrl,
      prNumber: result.prNumber,
      branch: branchName,
      isSimulated: result.isSimulated,
      message: result.message
    });
  } catch (err: any) {
    console.error('Error in createAiFixPr controller:', err);
    res.status(500).json({ message: 'Failed to create AI Fix PR', error: err.message });
  }
}
