import { Response } from 'express';
import { AuthenticatedRequest } from '../middleware/auth';
import { githubService } from '../services/githubService';
import { query } from '../config/db';
import { EventBus } from '../services/eventBus';
import { sendSafeError } from '../utils/securityUtils';

export async function createAiFixPr(req: AuthenticatedRequest, res: Response): Promise<void> {
  const { runId, repoUrl, filePath, fixDescription, proposedCode, projectId } = req.body;

  if (!req.user) {
    res.status(401).json({ message: 'Unauthorized.' });
    return;
  }

  try {
    // 1. Path traversal & input length validation
    if (filePath && (filePath.includes('..') || filePath.startsWith('/') || filePath.startsWith('\\'))) {
      res.status(400).json({ message: 'Invalid file path. Path traversal detected.' });
      return;
    }

    if (proposedCode && proposedCode.length > 100000) {
      res.status(400).json({ message: 'Proposed patch code exceeds maximum length of 100,000 characters.' });
      return;
    }

    // 2. Validate repository belongs to an authorized project for this user
    let targetProjectId = projectId;
    if (!targetProjectId && runId) {
      const prRes = await query(
        `SELECT p.project_id FROM pipeline_runs pr JOIN pipelines p ON pr.pipeline_id = p.id WHERE pr.id = $1`,
        [runId]
      );
      if (prRes.rowCount && prRes.rowCount > 0) targetProjectId = prRes.rows[0].project_id;
    }

    if (repoUrl && !targetProjectId) {
      const repoRes = await query(`SELECT project_id FROM repositories WHERE github_repo_url ILIKE $1 LIMIT 1`, [
        `%${repoUrl}%`,
      ]);
      if (repoRes.rowCount && repoRes.rowCount > 0) targetProjectId = repoRes.rows[0].project_id;
    }

    if (!targetProjectId && req.user.role !== 'Super Admin') {
      res.status(400).json({ message: 'Target project context is required for AI PR creation.' });
      return;
    }

    if (targetProjectId && req.user.role !== 'Super Admin') {
      const projRes = await query('SELECT owner_id FROM projects WHERE id = $1', [targetProjectId]);
      if (projRes.rowCount === 0) {
        res.status(404).json({ message: 'Project not found.' });
        return;
      }
      if (projRes.rows[0].owner_id !== req.user.id) {
        const pmRes = await query('SELECT 1 FROM project_members WHERE project_id = $1 AND user_id = $2', [
          targetProjectId,
          req.user.id,
        ]);
        if (!pmRes.rowCount || pmRes.rowCount === 0) {
          res.status(403).json({ message: 'Forbidden. You do not have authorization for this project.' });
          return;
        }
      }
    }

    const targetRepo = repoUrl || 'https://github.com/deploymate-org/deploymate-app';
    const targetFile = filePath || 'src/services/telemetry.ts';
    const branchName = `fix/ai-autofix-${Date.now().toString(36)}`;

    const patchCode =
      proposedCode ||
      `// AI Automated Patch generated by DEPLOYMATE Gemini AIOps Engine\n// Issue fix description: ${
        fixDescription || 'Resolved memory pool exhaust and runtime crash'
      }\n\nexport const sanitizeConfig = (cfg: any) => {\n  if (!cfg) return {};\n  return { ...cfg, timeoutMs: 5000, retryAttempts: 3 };\n};\n`;

    const prTitle = `[AIOps Auto-Fix] ${fixDescription || 'Automated Pipeline & Runtime Failure Remediation'}`;
    const prBody =
      `### 🤖 DEPLOYMATE Gemini AIOps Automated Patch\n\n` +
      `**Triggered by Pipeline Run:** \`${runId || 'PR-RUN-' + Math.floor(Math.random() * 1000)}\`\n\n` +
      `#### Root Cause & Remediation Summary:\n` +
      `${
        fixDescription ||
        'Identified connection exhaustion and missing error boundaries. Added sanitization and safe default fallbacks.'
      }\n\n` +
      `#### Target File:\n` +
      `\`${targetFile}\`\n\n` +
      `*Generated automatically by DEPLOYMATE Cloud Operations Platform.*`;

    const result = await githubService.createFixPullRequest({
      repoUrl: targetRepo,
      branchName,
      filePath: targetFile,
      fileContent: patchCode,
      prTitle,
      prBody,
    });

    // Record Audit Log entry
    await query(
      `INSERT INTO audit_logs (user_id, action, resource, details)
       VALUES ($1, $2, $3, $4)`,
      [
        req.user.id,
        'AI_FIX_PR_CREATED',
        `GitHubPR#${result.prNumber}`,
        JSON.stringify({ prUrl: result.prUrl, branch: branchName, runId, execution_mode: result.isSimulated ? 'SIMULATED' : 'LIVE' }),
      ]
    );

    // Emit EventBus event
    await EventBus.emit({
      eventType: 'AI_PULL_REQUEST_CREATED',
      source: 'ai',
      severity: 'INFO',
      resource: `GitHubPR#${result.prNumber}`,
      metadata: { prUrl: result.prUrl, branch: branchName, runId },
    });

    res.status(200).json({
      status: 'SUCCESS',
      prUrl: result.prUrl,
      prNumber: result.prNumber,
      branch: branchName,
      execution_mode: result.isSimulated ? 'SIMULATED' : 'LIVE',
      message: result.message,
    });
  } catch (err: any) {
    sendSafeError(res, err, 'Failed to create AI Fix PR', 500);
  }
}
